# These will be used when generating kubernetes entities
project-name: glitchy

domains:
  production: chatparty.io
  staging: vaharoni.com

# Supported: hetzner or digitalocean
infra: hetzner

# Only relevant for Digital Ocean. Determines the number of versions to keep for each docker image.
image-versions-to-keep: 5

registry-base-url: registry.vaharoni.com
registry-name: glitchy

# production and staging are supported by default
extra-remote-environments: []

# development and test are supported by default
extra-local-environments: []