apiVersion: v1
kind: ConfigMap
metadata:
  # Do not change the name - this is required by the Nginx Ingress Controller
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  use-proxy-protocol: "true"