apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hcloud-volumes-retain
provisioner: csi.hetzner.cloud
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true