apiVersion: stackgres.io/v1
kind: SGScript
metadata:
  name: create-db-script
  namespace: db-staging
spec:
  managedVersions: true
  continueOnError: false
  scripts:
  - name: create-database
    script: |
      CREATE DATABASE $PROJECT_NAME WITH OWNER postgres;
