apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: $MONOREPO_SERVICE_NAME
    env: $MONOREPO_ENV
  name: $MONOREPO_SERVICE_NAME
  namespace: $MONOREPO_NAMESPACE
spec:
  schedule: "$MONOREPO_PKG_CRON_SCHEDULE"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          volumes:
            - name: secret-injection-hook
              secret:
                secretName: $MONOREPO_SECRET_NAME
          containers:
            - image: $MONOREPO_IMAGE_PATH
              name: $MONOREPO_SERVICE_NAME
              command:
                - .devops/docker-entrypoints/node-exec.sh
              args:
                - devops
                - internal-curl
              env:
                - name: MONOREPO_ENV
                  value: $MONOREPO_ENV
                - name: MONOREPO_NAMESPACE
                  value: $MONOREPO_NAMESPACE
                - name: IS_KUBERNETES
                  value: 'true'
                - name: MONOREPO_BASE_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: $MONOREPO_SECRET_NAME
                      key: $MONOREPO_BASE_SECRET_KEY
              volumeMounts:
                - name: secret-injection-hook
                  mountPath: /etc/kubernetes/secrets
                  readOnly: true
              resources:
                requests:
                  memory: '250Mi'
          restartPolicy: Never
