apiVersion: batch/v1
kind: Job
metadata:
  name: $MONOREPO_DB_MIGRATE_JOB_NAME
  namespace: $MONOREPO_NAMESPACE
  labels:
    env: $MONOREPO_ENV
spec:
  template:
    spec:
      volumes:
        - name: secret-injection-hook
          secret:
            secretName: $MONOREPO_SECRET_NAME
      containers:
        - name: db-migrate-job
          image: $MONOREPO_IMAGE_PATH
          args:
            - 'db'
            - migrate-deploy
          env:
            - name: MONOREPO_ENV
              value: $MONOREPO_ENV
            - name: MONOREPO_NAMESPACE
              value: $MONOREPO_NAMESPACE
            - name: IS_KUBERNETES
              value: 'true'
          volumeMounts:
            - name: secret-injection-hook
              mountPath: /etc/kubernetes/secrets
              readOnly: true
          resources:
            requests:
              memory: '100Mi'
      restartPolicy: Never
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
