apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $MONOREPO_SERVICE_NAME
    env: $MONOREPO_ENV
  name: $MONOREPO_SERVICE_NAME
  namespace: $MONOREPO_NAMESPACE
spec:
  replicas: $MONOREPO_PKG_REPLICAS
  selector:
    matchLabels:
      app: $MONOREPO_SERVICE_NAME
  template:
    metadata:
      labels:
        app: $MONOREPO_SERVICE_NAME
        env: $MONOREPO_ENV
    spec:
      volumes:
        - name: secret-injection-hook
          secret:
            secretName: $MONOREPO_SECRET_NAME
      containers:
        - image: $MONOREPO_IMAGE_PATH
          name: $MONOREPO_SERVICE_NAME
          args:
            - "${MONOREPO_PROJECT_NAME}"
          env:
            - name: MONOREPO_ENV
              value: $MONOREPO_ENV
            - name: MONOREPO_NAMESPACE
              value: $MONOREPO_NAMESPACE
            - name: IS_KUBERNETES
              value: 'true'
            - name: MONOREPO_BASE_SECRET
              valueFrom:
                secretKeyRef:
                  name: $MONOREPO_SECRET_NAME
                  key: $MONOREPO_BASE_SECRET_KEY
          volumeMounts:
            - name: secret-injection-hook
              mountPath: /etc/kubernetes/secrets
              readOnly: true
          startupProbe:
            httpGet:
              path: /healthz
              port: $MONOREPO_PKG_PORT
            failureThreshold: 50
            periodSeconds: 2
          resources:
            requests:
              memory: '250Mi'
