apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  namespace: db-staging
  name: db-staging
spec:
  postgres:
    version: '17.4'
    # extensions:
    # - name: 'pg_repack'
    # - name: 'pg_trgm'
  instances: 1
  # sgInstanceProfile: 'size-m'
  profile: 'testing'
  pods:
    persistentVolume:
      size: '10Gi'
      storageClass: 'hcloud-volumes-retain'
    scheduling:
      tolerations:
        - key: "stackgres"
          operator: "Exists"
          effect: "NoSchedule"
  configurations:
    # sgPostgresConfig: 'pgconfig'
    # sgPoolingConfig: 'poolconfig'
    backups:
    - sgObjectStorage: 'backupconfig'
      # cronSchedule: '30 02 */4 * *'
      cronSchedule: '30 02 * * *'
      retention: 4
  # distributedLogs:
  #   sgDistributedLogs: 'distributedlogs'
  managedSql:
    scripts:
      - sgScript: create-db-script
  postgresServices:
    primary:
      type: ClusterIP
    replicas:
      type: ClusterIP
  prometheusAutobind: true
