architecture: replication
global:
  defaultStorageClass: hcloud-volumes-retain
master:
  resources: 
    requests:
      cpu: 1
      memory: 256Mi
    limits:
      cpu: 3
      memory: 1024Mi
replica:
  replicaCount: 1
  resources: 
    requests:
      cpu: 1
      memory: 256Mi
    limits:
      cpu: 3
      memory: 1024Mi  
