[project]
name = "db"
version = "0.1.0"
description = ""
authors = []
requires-python = ">=3.12"
dependencies = ["prisma (>=0.15.0,<0.16.0)"]

[tool.devops.scripts]
generate = "prisma generate --generator python-client"
